import { TermWindow } from "@/components/TermWindow";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { api } from "@/convex/_generated/api";
import { useAuth } from "@/hooks/use-auth";
import { useAction } from "convex/react";
import { Loader2, Send, Sparkles, Trash2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

type Msg = { role: "user" | "assistant"; content: string };

const SUGGESTIONS = [
  "Is this brand actually sustainable? How can I tell?",
  "How do I wash clothes so they last longer?",
  "What certifications should I look for?",
  "Best way to repair a holey sweater?",
];

export default function AiChat() {
  const { user } = useAuth();
  const ask = useAction(api.ai.ask);
  const [messages, setMessages] = useState<Msg[]>([
    {
      role: "assistant",
      content:
        "Ask me anything about sustainable fashion — brands, materials, repair, or your rewearing streak. I'm here to help you wear it again.",
    },
  ]);
  const [input, setInput] = useState("");
  const [pending, setPending] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({
      top: scrollRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages, pending]);

  const send = async (text: string) => {
    const question = text.trim();
    if (!question || pending) return;
    setInput("");
    setMessages((prev) => [...prev, { role: "user", content: question }]);
    setPending(true);
    try {
      const history = messages
        .slice(-8)
        .map((m) => ({ role: m.role, content: m.content }));
      const { answer } = await ask({ question, history });
      setMessages((prev) => [...prev, { role: "assistant", content: answer }]);
    } catch (err) {
      toast.error(
        err instanceof Error
          ? err.message.replace(/^Uncaught Error: /, "")
          : "AI request failed.",
      );
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content:
            "⚠ Connection to the fashion brain failed. Try again in a moment.",
        },
      ]);
    } finally {
      setPending(false);
    }
  };

  const reset = () =>
    setMessages([
      {
        role: "assistant",
        content:
          "Ask me anything about sustainable fashion — brands, materials, repair, or your rewearing streak. I'm here to help you wear it again.",
      },
    ]);

  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="text-xs text-muted-foreground">
          <span className="text-ok">$</span> ./ai-chat --ask
        </p>
        <h1 className="mt-1 text-2xl font-semibold tracking-tight">
          Ask about sustainable fashion
        </h1>
        <p className="text-sm text-muted-foreground">
          Answers are generated by an AI model grounded in sustainable-fashion
          knowledge. Verify brand claims before you buy.
        </p>
      </div>

      <TermWindow
        title="assistant --sustainable-fashion"
        className="flex flex-col"
        bodyClassName="p-0 sm:p-0 flex flex-col"
      >
        <div
          ref={scrollRef}
          className="term-scroll max-h-[55vh] min-h-[320px] flex-1 overflow-y-auto p-4 sm:p-6"
        >
          <div className="flex flex-col gap-4">
            {messages.map((m, i) => (
              <div key={i} className="flex flex-col gap-1">
                <span
                  className={
                    m.role === "user"
                      ? "text-xs font-semibold text-primary"
                      : "text-xs font-semibold text-ok"
                  }
                >
                  {m.role === "user"
                    ? `${user?.name || user?.email || "you"}@wardrobe:~$`
                    : "sustain-ai >"}
                </span>
                <div
                  className={
                    m.role === "user"
                      ? "rounded-sm border border-primary/30 bg-primary/5 px-3 py-2 text-sm leading-relaxed"
                      : "rounded-sm border border-ok/25 bg-ok/5 px-3 py-2 text-sm leading-relaxed"
                  }
                >
                  {m.content}
                </div>
              </div>
            ))}
            {pending && (
              <div className="flex flex-col gap-1">
                <span className="text-xs font-semibold text-ok">
                  sustain-ai &gt;
                </span>
                <div className="rounded-sm border border-ok/25 bg-ok/5 px-3 py-2">
                  <span className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Loader2 className="size-3.5 animate-spin" /> thinking…
                  </span>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* suggestions (only when only greeting present) */}
        {messages.length <= 1 && !pending && (
          <div className="flex flex-wrap gap-2 border-t border-border px-4 py-3">
            {SUGGESTIONS.map((s) => (
              <button
                key={s}
                onClick={() => send(s)}
                className="rounded-sm border border-border bg-muted px-2.5 py-1.5 text-xs text-muted-foreground transition-colors hover:border-ok/50 hover:text-foreground"
              >
                {s}
              </button>
            ))}
          </div>
        )}

        <form
          onSubmit={(e) => {
            e.preventDefault();
            send(input);
          }}
          className="flex items-center gap-2 border-t border-border bg-muted/40 p-3 sm:px-4"
        >
          <span className="hidden text-sm text-ok sm:block">$</span>
          <Input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="e.g. is cotton or polyester worse?"
            disabled={pending}
            className="flex-1"
            maxLength={1000}
          />
          <Button
            type="submit"
            size="icon"
            disabled={pending || !input.trim()}
            aria-label="Send"
          >
            {pending ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Send className="size-4" />
            )}
          </Button>
          <Button
            type="button"
            variant="outline"
            size="icon"
            onClick={reset}
            aria-label="Reset chat"
          >
            <Trash2 className="size-4" />
          </Button>
        </form>
      </TermWindow>

      <p className="flex items-center gap-1.5 text-xs text-muted-foreground">
        <Sparkles className="size-3.5 text-warn" />
        Powered by Groq · answers are AI-generated, not gospel.
      </p>
    </div>
  );
}
